driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  # - name: ubuntu-15.04
  # - name: centos-5.11
  # - name: centos-6.6
  - name: centos-7.1
    run_list:
      - recipe[nginx_service_test::nginx_repo]

suites:
  - name: example
    run_list:
      - recipe[nginx::example]

  - name: service_single
    run_list:
      - recipe[nginx_service_test::single]

  - name: service_multi
    run_list:
      - recipe[nginx_service_test::multi]

  - name: service_single_upstream
    run_list:
      - recipe[nginx_service_test::nginx_repo]
      - recipe[nginx_service_test::single]
