---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  product_name: chef
  solo_rb:
    treat_deprecation_warnings_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazonlinux-2
    driver_config:
      box: ywatase/amzn2
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: fedora-28
  - name: opensuse-leap-15
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: distro
    run_list:
      - recipe[test::distro]
    excludes:
      - centos-7
  - name: repo
    run_list:
      - recipe[test::repo]
    excludes:
      - fedora-28
  - name: epel
    run_list:
      - recipe[test::epel]
    includes:
      - amazonlinux-2
      - centos-7
  - name: passenger
    run_list:
      - recipe[test::passenger]
    excludes:
      - amazonlinux-2
      - centos-7
      - fedora-28
      - opensuse-leap-15

  - name: source
    run_list:
      - recipe[test::source]
  - name: source
    run_list:
      - recipe[test::source]
  - name: stream
    run_list:
      - recipe[test::stream]
