---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.9
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.7
  - name: centos-7.2

suites:
  - name: example
    run_list:
      - recipe[nginx_service_test::common]
      - recipe[nginx::example]

  - name: service_single
    run_list:
      - recipe[nginx_service_test::common]
      - recipe[nginx_service_test::single]

  - name: service_multi
    run_list:
      - recipe[nginx_service_test::common]
      - recipe[nginx_service_test::multi]

  - name: service_single_upstream
    run_list:
      - recipe[nginx_service_test::common]
      - recipe[nginx_service_test::nginx_repo]
      - recipe[nginx_service_test::single]
