name             'nginx'
source_url       'https://github.com/sous-chefs/nginx'
issues_url       'https://github.com/sous-chefs/nginx/issues'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
chef_version     '>= 15.3'
license          'Apache-2.0'
description      'Installs and configures nginx'
version          '12.1.1'

supports 'amazon'
supports 'centos'
supports 'fedora'
supports 'debian'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'ubuntu'
supports 'suse'
supports 'opensuse'
supports 'opensuseleap'
