name              'nginx'
maintainer        'Mike Fiedler'
maintainer_email  'miketheman@gmail.com'
license           'Apache 2.0'
description       'Installs and configures nginx'
version           '2.99.0'
